log_dir: "/experiments/stargan-v2/esdall_emotion_classifier_experiment_alternate_epochs200/"
device: "cuda"
epochs: 200
save_freq: 1
batch_size: 256
pretrained_model: ""
load_only_params: false
fp16_run: true
domain: "emotions"

train_data: "/dataset/ESD/Emotional Speech Dataset (ESD)/English_sub_set/train_list.txt"
val_data: "/dataset/ESD/Emotional Speech Dataset (ESD)/English_sub_set/val_list.txt"

F0_path: "/StarGAN_v2/Utils/JDC/bst.t7"
ASR_config: "/StarGAN_v2/Utils/ASR/config.yml"
ASR_path: "/StarGAN_v2/Utils/ASR/epoch_00100.pth"

optimizer_params:
  lr: 0.0001

loss_params:
  lambda_classification_loss: 1.0